### ISSUE TITLE
withAuth without scope not working

### ISSUE THREAD

**Issue by mitjade** [kkemple/graphql-auth#1]
Im trying to integrate this package into an existing graphql `express` server.

```
users: withAuth((root, args, context) => { ... }),
```
gives me an error:
```
error { TypeError: Cannot read property 'length' of null
    at /.../node_modules/graphql-auth/index.js:42:8
   ...
``` 

If I call
```
users: withAuth([], (root, args, context) => { ... }),
```
It works ok.

**Comment by kkemple** [comment]
hey @mitjade, thanks for submitting, I will take a look and see what I can dig up

**Comment by kkemple** [comment]
a new version `0.0.4` has been pushed and this should be resolved now
sorry for the delay!
