### ISSUE TITLE
Support wildcards

### ISSUE THREAD

**Issue by mschipperheyn** [kkemple/graphql-auth#14]
Judging by the code, you need to explicitly specify all scopes. But e.g. admins usually have access to all scopes. Would be nice if you could specify shortcuts like that

```
const scopes = {
    ADMIN: ['*'],
    EDITOR: [
        'user:*',
        'todo:*'
    ],
    ENDUSER: [
        'user:view:self',
        'user:update:self',
        'user:create',
        'todo:*'
    ]
}
```

**Comment by kkemple** [comment]
want to give this a go? there isn't a lot of code in the project, and im happy to walk you through implementation details

**Comment by mschipperheyn** [comment]
Hey @kkemple sorry. We decided to drop this and stick to a role based authorization structure and I'm too slammed to pick this up on the side.

**Comment by artgibson** [comment]
@mschipperheyn to resolve this should be handled right here: https://github.com/kkemple/graphql-auth/blob/master/index.js#L22
