### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by OliverCole** [kkemple/graphql-auth#15]
Hi!

I’d love to use this library, but there’s no license specified. Would you mind committing one?

Thanks!

**Comment by srvmux** [comment]
on their [NPM](https://www.npmjs.com/package/graphql-auth) homepage it says MIT

**Comment by OliverCole** [comment]
Thanks - 7 months ago we needed an actual LICENSE text checked in to the repo, but since then we’ve been told we can rely on the package.json field.

You may still want to check in a LICENSE file for completeness though.
